### ISSUE TITLE
How to compile this kernel

### ISSUE THREAD

**Issue by ccccoisini** [Pzqqt/android_kernel_xiaomi_marble#1]
你好, 我是一个小白, 我在使用下面的脚本进行编译后 刷入手机无法开机
Hi, I'm a noob, I'm using the following script and after compiling it, the phone won't turn on when I swipe it.
`#!/bin/bash
args="-j$(nproc --all) \
	O=out \
	ARCH=arm64 \
	CLANG_TRIPLE=aarch64-linux-gnu- \
	CROSS_COMPILE=aarch64-linux-gnu- \
	CC=/home/ubuntu/llvm13/clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04/bin/clang \
	CROSS_COMPILE_ARM32=arm-linux-gnueabi- "
	make ${args} marble_defconfig
	make ${args}`

请问可以告诉我一下该如何编译吗?我非常愿意对你的项目进行捐赠
Can you please tell me how to compile it instead? I would be happy to donate to your project!

**Comment by Pzqqt** [comment]
下载 [clang-r416183b.tar.gz](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/428d18d9732aa7ebfcaed87a582d86155db878d4/clang-r416183b.tar.gz)

解压，然后把解压后的bin目录的绝对路径添加到PATH环境变量之前。举例：

```shell
export PATH=/home/pzqqt/build_toolchain/clang-r416183b-12.0.5/bin:${PATH}
```

开始编译：

```shell
make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out mrproper
make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out marble_defconfig
make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out -j$(nproc --all)
```

~~注意：对于android12-5.10内核，必须使用指定版本（12.0.5）的clang，使用其他版本的clang编译的内核一定不会开机。~~

最后，本人拒绝任何形式的捐赠。

**Comment by ccccoisini** [comment]
谢谢你,好人一生平安
