### ISSUE TITLE
The remaining storage in settings shows an error

### ISSUE THREAD

**Issue by M3351AN** [Pzqqt/android_kernel_xiaomi_marble#10]
This issue occurs after using kernel flasher to flash the ak3 kernel package of 2.7 version melt kernel.
My device actually only has 256Gb of storage space, but it shows that the maximum 2TB is full.
![Screenshot_2024-05-09-22-44-15-502_com android settings](https://github.com/Pzqqt/android_kernel_xiaomi_marble/assets/65479796/03004870-2094-444b-97de-ab20363ace6b)
![Screenshot_2024-05-09-22-45-56-096_com miui securitycenter](https://github.com/Pzqqt/android_kernel_xiaomi_marble/assets/65479796/36bf5749-ae35-4bbb-9e8e-8ecc6028af62)

This issue only occurs in settings. The remaining storage space is displayed normally but root space displayed error in other file managers and does not cause any problems in actual use.
![Screenshot_2024-05-09-23-01-51-769_bin mt plus-edit](https://github.com/Pzqqt/android_kernel_xiaomi_marble/assets/65479796/a8d7e6f6-888c-4af4-9802-ed14976f605b)

Since I haven't had a chance to use my computer recently, I didn't do any further troubleshooting to see if the problem was caused by flashing the kernel.
Config: Use ksu, display accurate battery, do not lock screen refresh rate 
Device: poco f5 23049PCD8G 
OS: MIUI 14.0.23.0 TMRCNXM(China)

**Comment by Pzqqt** [comment]
https://kernelsu.org/guide/faq.html#why-does-my-device-show-wrong-storage-size
