### ISSUE TITLE
stack frame size (2080) exceeds limit (2048) in 'brd get_frame data' [-werror,-wframe-larger-than]

### ISSUE THREAD

**Issue by mjuned47** [Pzqqt/android_kernel_xiaomi_marble#15]
When compiling with clang llvm-r522817

drivers/input/touchscreen/goodix_9916r/goodix_brl_hw.c error: stack frame size (2080) exceeds limit (2048) in 'brld_get_framedata' [-werror,-wframe-larger-than]

**Comment by mjuned47** [comment]
../drivers/input/touchscreen/goodix_9916r/goodix_brl_hw.c:1303:12: error: stack frame size (2080) exceeds limit (2048) in 'brld_get_framedata' [-Werror,-Wframe-larger-than]
static int brld_get_framedata(struct goodix_ts_core *cd,
           ^
1 error generated.
make[5]: *** [../scripts/Makefile.build:279: drivers/input/touchscreen/goodix_9916r/goodix_brl_hw.o] Error 1

**Comment by Pzqqt** [comment]
It’s better to ask Google such a simple question than to ask me.

**Comment by mjuned47** [comment]
Can you put a link of toolchain which you use for compiling this kernel currently?

**Comment by mjuned47** [comment]
@Pzqqt please put a link of toolchain. Im not sure suppress this error might cause kernel not to boot
Or please suggest workaround for this issue.
