### ISSUE TITLE
Update the kernel from 3.0 to 3.1 was failed

### ISSUE THREAD

**Issue by davx2012** [Pzqqt/android_kernel_xiaomi_marble#16]
Model : Redmi Note 12T
OS : MIUI 14 EEA 14.0.9.0
TWRP : Skkk A14 8.6

I flashed the latest kernel via this twrp. But was failed at the split image step. The log show Updater error code : 1. So I flashed the 3.0 kernel for rollback the kernel. It is compatibility issue? But I flashed all old version kernel was normal.

**Comment by Pzqqt** [comment]
> Model : Redmi Note 12T OS : MIUI 14 EEA 14.0.9.0 TWRP : Skkk A14 8.6
> 
> I flashed the latest kernel via this twrp. But was failed at the split image step. The log show Updater error code : 1. So I flashed the 3.0 kernel for rollback the kernel. It is compatibility issue? But I flashed all old version kernel was normal.

Read the changelog carefully, OK?
