### ISSUE TITLE
crDroid 10.8 is not supported

### ISSUE THREAD

**Issue by msycn** [Pzqqt/android_kernel_xiaomi_marble#18]
Dear Pzqqt,

Thank you for your continuous outstanding development work. I am currently using the Melt 3.1 kernel on crDroid 10.8 without any issues. However, when I tried flashing the latest 3.2 version using TWRP, the script showed that this ROM is not supported.

To Reproduce:

1.  Use crDroid 10.8
2. Flash Melt kernel 3.2 using TWRP
3. Script displays a message saying not supported is rom

Expected behavior:

The kernel should flash successfully on crDroid 10.8.

Screenshots:

(Not available)

Additional context:

Should I revert to the stock boot image and flash again, or do you have a better solution?
Thank you!

**Comment by Pzqqt** [comment]
So please think about why the installer prompts you that your ROM is not supported? Is it a bug in the installer? Or is it a deliberate restriction by the developer?

Before installing the Melt Kernel next time, please read the changelog and notes carefully.
