### ISSUE TITLE
Bootloop with PixelOS

### ISSUE THREAD

**Issue by sooyongjie** [Pzqqt/android_kernel_xiaomi_marble#19]
My Redmi Note 12 Turbo went into bootloop after installing v3.2 (last month). I could not even boot into TWRP, which is a first time for me. I was able to flash the stock PixelOS recovery to get it to boot. Reinstalling TWRP makes it bootloop again 😿

Kernel version: 3.2
TWRP: SKKK https://t.me/SKKKTWRP/205
ROM: PixelOS 05 Oct 24 build https://pixelos.net/download/marble

**Comment by Pzqqt** [comment]
Use the latest version, bug reports for older versions will not be accepted.
