### ISSUE TITLE
添加kernelsu后编译失败

### ISSUE THREAD

**Issue by ccccoisini** [Pzqqt/android_kernel_xiaomi_marble#2]
你好, 我在添加kernelsu后编译遇到了些问题,我尝试google搜索没有得到解决,请问我该修改哪里使得编译成功,麻烦你了,谢谢
`ld.lld: error: duplicate symbol: ksu_queue_work
>>> defined in drivers/built-in.a(staging/kernelsu/ksu.o)
>>> defined in drivers/built-in.a(kernelsu/ksu.o)

ld.lld: error: duplicate symbol: ksu_handle_execveat
>>> defined in drivers/built-in.a(staging/kernelsu/ksu.o)
>>> defined in drivers/built-in.a(kernelsu/ksu.o)

ld.lld: error: duplicate symbol: kernelsu_init
>>> defined in drivers/built-in.a(staging/kernelsu/ksu.o)
>>> defined in drivers/built-in.a(kernelsu/ksu.o)

ld.lld: error: duplicate symbol: kernelsu_exit
>>> defined in drivers/built-in.a(staging/kernelsu/ksu.o)
>>> defined in drivers/built-in.a(kernelsu/ksu.o)

ld.lld: error: duplicate symbol: __initstub__kmod_ksu__264_77_kernelsu_init6
>>> defined in drivers/built-in.a(staging/kernelsu/ksu.o)
>>> defined in drivers/built-in.a(kernelsu/ksu.o)

ld.lld: error: duplicate symbol: ksu_show_allow_list
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_get_app_profile
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_set_app_profile
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: persistent_allow_list
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: __ksu_is_allow_uid
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_uid_should_umount
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_get_root_profile
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_get_allow_list
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: do_save_allow_list
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: do_load_allow_list
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_prune_allowlist
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_load_allow_list
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_allowlist_init
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: ksu_allowlist_exit
>>> defined in drivers/built-in.a(staging/kernelsu/allowlist.o)
>>> defined in drivers/built-in.a(kernelsu/allowlist.o)

ld.lld: error: duplicate symbol: is_manager_apk
>>> defined in drivers/built-in.a(staging/kernelsu/apk_sign.o)
>>> defined in drivers/built-in.a(kernelsu/apk_sign.o)

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
make[1]: *** [/home/ubuntu/paradox/Makefile:1365: vmlinux] Error 1
make[1]: Leaving directory '/home/ubuntu/paradox/out'
make: *** [Makefile:196: __sub-make] Error 2`

**Comment by Pzqqt** [comment]
我的内核源码里明明添加的有KernelSU（只是 [默认没有启用](https://github.com/Pzqqt/android_kernel_xiaomi_marble/commit/b94c0ea5f977759af38857618cac7d6e2ea932b2)），为什么要重复添加？

**Comment by ccccoisini** [comment]
谢谢你 我是直接安装kernelsu提供的命令操作的 我的问题
