### ISSUE TITLE
good sir please

### ISSUE THREAD

**Issue by epokuser** [Pzqqt/android_kernel_xiaomi_marble#20]
} else if (IS_ENABLED(CONFIG_TRANSPARENT_HUGEPAGE)) {
to 
+	} else if (IS_ENABLED(CONFIG_TRANSPARENT_HUGEPAGE)
+		   && IS_ALIGNED(len, PMD_SIZE)) {

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d4148aeab412432bf928f311eca8a2ba52bb05df

merge it

**Comment by Pzqqt** [comment]
Cannot be merged, because the commits before this one does not exist in the 5.10.x code.
