### ISSUE TITLE
New function suggestion

### ISSUE THREAD

**Issue by ZIFEIYU3zifeiyu** [Pzqqt/android_kernel_xiaomi_marble#21]
Can you try to add it to Melt? I think this is a good attempt.[ksu_module_susfs](https://github.com/sidex15/ksu_module_susfs)

**Comment by Pzqqt** [comment]
> Can you try to add it to Melt? I think this is a good attempt.[ksu_module_susfs](https://github.com/sidex15/ksu_module_susfs)

I'm getting more and more disgusted with this shit thing.
