### ISSUE TITLE
Add CONFIG_NETFILTER_XT_TARGET_HL=y  to build config?

### ISSUE THREAD

**Issue by 00svd00** [Pzqqt/android_kernel_xiaomi_marble#3]
Can you please add CONFIG_NETFILTER_XT_TARGET_HL=y to build config?
It's needed to control ttl through iptables (xt_HL.ko kernel module)

**Comment by Pzqqt** [comment]
Already added in v2.2.

https://github.com/Pzqqt/android_kernel_xiaomi_marble/commit/e03595bec8c3ed5cfc620582b82568ce8b4675af

And it has been compiled into the kernel image, so you can use this feature directly without loading additional kernel modules (*.ko).

**Comment by 00svd00** [comment]
Seems that I've missed it somehow. Everything works, thank you very much for your work!
