### ISSUE TITLE
please help me T T， I can't compile the kernel

### ISSUE THREAD

**Issue by moculll** [Pzqqt/android_kernel_xiaomi_marble#4]
after cloned this repostory, I downloaded  clang13.0.1 for compiling, and I used these code to make Image
`
$ make \
	O=out \
	clean \
	mrproper \
	CC=clang \
	AR=llvm-ar \
	NM=llvm-nm \
	OBJCOPY=llvm-objcopy \
	OBJDUMP=llvm-objdump \
	READELF=llvm-readelf \
	OBJSIZE=llvm-size \
	STRIP=llvm-strip \
	HOSTCC=clang \
	HOSTCXX=clang++ \
	${DEVICE}_defconfig
  
$ make \
	O=out \
	CC=clang \
	AR=llvm-ar \
	NM=llvm-nm \
	OBJCOPY=llvm-objcopy \
	OBJDUMP=llvm-objdump \
	READELF=llvm-readelf \
	OBJSIZE=llvm-size \
	STRIP=llvm-strip \
	HOSTCC=clang \
	HOSTCXX=clang++ \
	-j$(nproc --all)
`
but it can't be compiled out or the Image can't boot the device, so I want to know if you guys could give me the clangtools you are using T T,thank you guys T T

**Comment by Pzqqt** [comment]
https://github.com/Pzqqt/android_kernel_xiaomi_marble/issues/1

**Comment by moculll** [comment]
thank you so much, i was such a fish at that time
